# Generated by Django 2.2 on 2019-04-02 09:05

from django.db import migrations, models
import django_unixdatetimefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=500)),
                ('date_create', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
